FROM python:3.14.0-alpine3.22

WORKDIR /code

# Install build dependencies
RUN apk add --no-cache gcc musl-dev libffi-dev python3-dev build-base

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app

# Create a non-root user and group
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
# Fix permissions for the app directory recursively (include #allfiles/folders inside)
RUN chown -R appuser:appgroup /code

# Switch to non-root user
USER appuser

CMD ["fastapi", "run", "app/main.py", "--port", "80"]
